### ISSUE TITLE
need an answer

### ISSUE THREAD

**Issue by jimblue** [kristerkari/observable-redux-json-api#23]
Hi @kristerkari ,

I'm trying to reach you for more than a month without getting any answer.
Because I'm not sure you got my emails or message I'm writing you here.

Can you please help me out and answer my request on this repo:

https://github.com/kristerkari/stylelint-scss/issues/109

Thank you so much

**Comment by kristerkari** [comment]
@jimblue please stop spamming.

My open source repositories have absolutely nothing to do with your website's SEO.

**Comment by jimblue** [comment]
Sorry you took my message this way but i'm trying to reach you for more than a month without success on the original post.

I've already asked Github support of course, but the currently don't migrate name if there is a modification. They suggest me to ask directly to the concerned Github user.

Can you please answer my request, it's a 10sec operation, I don't see where it could be a problem for you. Thank you.
